repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.0
    hooks:
      - id: terraform_fmt
        always_run: true
      - id: terraform_validate
        files: '\.tf$'
        args: 
        - --tf-init-args=-backend=false
        
